import { preNormalizarProduto } from "./utils/normalizador-v25.js";

const exemplos = [
  "WHEY SH.MASS 800 CHOC.BAD BOY",
  "TOTELLE CICLO 1MG+0,250MG 28DR",
  "SUMAX 10MG SPR 2DOS 0,2ML",
  "TIRA LEITE BOMB.PROLACTA PROMI",
  "TESOURA MUND FLEX CURV FIN 1UN",
  "CLOR.METFORMINA 500MG/30CPR GE",
  "ADOC.LINEA CULINARIO 70G /",
  "CRE.FRUCTIS TR.CHOQUE CAB.SECO",
  "PROT MAMILO LILLO SIL 4311 1UN",
  "JOELHEIRA NEOP.PAT.C/REF.C/SUP",
  "ESC.D.REACH CONTROL 40 G MAC /",
  "CURAT.BAND-AID BOB ESPONJA C/2",
  "FISIOGEL A.I CR ALIV CALM 30G",
  "CETOC+BETAM POM DERM 30G",
  "LOC.HID.G.DOUR.PROT.LEITE 500M"
];

for (const exemplo of exemplos) {
  console.log(`${exemplo}\n→ ${preNormalizarProduto(exemplo)}\n`);
}
